I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1455, in script
    j "Damn, what is that guy up there yelling about?"
IOError: Couldn't find file 'pills_coffee_shout.wav'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1455, in script
    j "Damn, what is that guy up there yelling about?"
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/ast.py", line 604, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/exports.py", line 1122, in say
    who(what, interact=interact)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/character.py", line 841, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/character.py", line 690, in do_display
    **display_args)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/character.py", line 493, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/ui.py", line 277, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/display/core.py", line 2425, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/display/core.py", line 2725, in interact_core
    renpy.audio.audio.interact()
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/audio/audio.py", line 919, in interact
    periodic()
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/audio/audio.py", line 853, in periodic
    c.periodic()
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/audio/audio.py", line 400, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/audio/audio.py", line 66, in load
    rv = renpy.loader.load(fn)
  File "/Users/gerritfeenstra/repos/pills/renpy-6.99.10-sdk/renpy/loader.py", line 533, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'pills_coffee_shout.wav'.

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 6.99.10.1227
pills 0.0
